fix: linting, license dates, and import statements in react
NationalSecurityAgency/skills-client pull request #110
Opened 2021-04-05 23:43 UTC by evenstensberg

Leaving as it is

2021-04-23 15:06 UTC, rmmayo requested changes
hi @evenstensberg - thanks for another contribution!  After looking over the changes, we *think* that the copyright years for existing files are supposed to retain the year that they were created (from reading [this SO question](https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated)), so we would like to change the `Copyright 2021 SkillTree` changes back to `Copyright 2020 SkillTree`, and also [this](https://github.com/NationalSecurityAgency/skills-client/pull/110/files) change to `es2021` seems to have broken the build.  The other changes to `skills-client-react` look good - thank you!

2021-04-23 15:07 UTC, rmmayo commented on skills-client-integration/skills-int-client-ng/tsconfig.base.json
> +    "module": "es2021",
@evenstensberg  this change seems to have broken the build.

2021-04-23 16:22 UTC, evenstensberg commented
I'll open another PR!

2021-04-23 16:26 UTC, evenstensberg commented
There we go, PTAL

2021-04-23 17:08 UTC, rmmayo approved these changes
Looks good, thanks!  👍

2021-04-23 17:08 UTC, merged

2021-04-23 17:09 UTC, evenstensberg commented
Do you have any other open issues I can help with?

2021-04-23 17:51 UTC, sudo-may commented
@evenstensberg awesome!! Feel free to grab [#567](https://github.com/NationalSecurityAgency/skills-service/issues/567) and then anything labeled with "[good first issue](https://github.com/NationalSecurityAgency/skills-service/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)" would make sense as well; you will probably want to also take a look at the [Development Environment](https://code.nsa.gov/skills-docs/contribution/devEnv.html#prerequisites) portion of the docs.

2021-04-23 18:04 UTC, sudo-may commented
@evenstensberg on a second thought [#129](https://github.com/NationalSecurityAgency/skills-service/issues/129) maybe a lower hanging fruit

2021-04-24 10:33 UTC, evenstensberg commented
Thx! I'll get back to you once I have time!